config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'
  get 'restaurants/stadistics', to: 'restaurants#stadistics'
  resources :restaurants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :id, uniqueness: true
  validates :rating, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :lng, presence: true, numericality: {
    greater_than_or_equal_to: -180,
    less_than_or_equal_to: 180
  }
  validates :lat, presence: true, numericality: {
    greater_than_or_equal_to: -90,
    less_than_or_equal_to: 90
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  include RestaurantsHelper
  # Skip Athenticity token to be able to test the API
  # by external resources
  skip_before_action :verify_authenticity_token
  before_action :set_restaurant, only: %i[show edit update destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show; end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit; end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: { errors: @restaurant.errors }, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: { errors: @restaurant.errors }, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def stadistics
    # An instance of the Boundary helper class
    # It will validate the constraints required for the parameters
    # taken directly from the ´params´ Hash
    boundary = Boundary.new params

    if boundary.valid?
      # The boundary circle has proper format

      # Making use of PostGIS extension the following query
      # returns a result set as follows:
      # {
      #   count: Count of restaurants that fall inside the circle with center [x,y] y radius z,
      #   avg: Average rating of restaurant inside the circle,
      #   std: Standard deviation of rating of restaurants inside the circle
      # }
      # Taking into account that ´radius´ must be specified in meters
      query = ActiveRecord::Base.sanitize_sql_array [
        %{
          SELECT COUNT(*), CAST(AVG(rating) AS FLOAT), CAST(STDDEV(rating) AS FLOAT) AS std
          FROM restaurants
          WHERE ST_DWithin(ST_SetSRID(ST_MakePoint(lng, lat), 4326), ST_MakePoint(?, ?)::geography, ?)
        },
        boundary.longitude,
        boundary.latitude,
        boundary.radius
      ]

      result = ActiveRecord::Base.connection.execute(query).first

      # The resulting JSON is rendered as response
      render json: result

    else
      # The parameters have no the appropiate format

      # A JSON with the description of the errors is rendered as response
      render json: { errors: boundary.errors }, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def restaurant_params
    params.require(:restaurant).permit(:id, :rating, :name, :site, :email, :phone, :street, :city, :state, :lat, :lng)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  # Helper class to validate a circle coordinates
  # The parameters are taken directly from the `params` Hash
  # latitude: x
  # longitude: y
  # radius: z
  class Boundary
    include ActiveModel::Validations

    attr_accessor :latitude, :longitude, :radius

    validates :longitude, presence: true, numericality: {
      greater_than_or_equal_to: -180,
      less_than_or_equal_to: 180
    }
    validates :latitude, presence: true, numericality: {
      greater_than_or_equal_to: -90,
      less_than_or_equal_to: 90
    }
    validates :radius, presence: true, numericality: { greater_than_or_equal_to: 0 }

    def initialize(params)
      @longitude = params[:longitude]
      @latitude = params[:latitude]
      @radius = params[:radius]
    end
  end
end

app/views/layouts/_nav.html.slim
.navbar-brand
  = link_to root_path, class: 'navbar-item'
    span.icon.is-large: span.fa-stack
      i.fas.fa-circle.fa-stack-2x
      i.fas.fa-hotel.fa-stack-1x.has-text-success
    span.is-size-2.has-text-weight-bold style="letter-spacing: 5px;"
      | Melp

app/views/layouts/application.html.slim
doctype html
html
  head
    title Melp on Rails
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'https://jenil.github.io/bulmaswatch/litera/bulmaswatch.min.css', media: 'all'
    = stylesheet_link_tag    'https://use.fontawesome.com/releases/v5.3.1/css/all.css',
      integrity: 'sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU', crossorigin:'anonymous'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav.navbar.is-success role="navigation" aria-label="main navigation"
      == render partial: 'layouts/nav'
    = yield

app/views/restaurants/_form.html.slim
= form_for @restaurant do |f|
  - if @restaurant.errors.any?
    #error_explanation
      h2 = "#{pluralize(@restaurant.errors.count, "error")} prohibited this restaurant from being saved:"
      ul
        - @restaurant.errors.full_messages.each do |message|
          li = message

  .columns
    .column
      .field
        = f.label :name, 'Nombre'
        .control
          = f.text_field :name,
          class: 'input',
          required: true
    .column
      .field
        = f.label :id
        .control
          = f.text_field :id,
            class: 'input',
            required: true,
            placeholder: '{8}-{4}-{4}-{4}-{12}',
            pattern: '[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}',
            title: '{8}-{4}-{4}-{4}-{12}'
  .columns
    .column.is-1
      .field
        = f.label :rating
        .control: .select
          = f.select :rating,
          options_for_select(0..5),
          required: true
    .column
      .field
        = f.label :site, 'Sitio Web'
        .control
          = f.text_field :site,
            placeholder: 'https://ejemplo-de-sitio-web.com',
            class: 'input',
            required: true
    .column
      .field
        = f.label :email, 'Correo electrónico'
        .control
          = f.email_field :email,
            placeholder: 'alguien@ejemplo.com',
            class: 'input',
            required: true
    .column
      .field
        = f.label :phone, 'Teléfono'
        .control
          = f.text_field :phone, class: 'input', required: true
  .columns
    .column
      .field
        = f.label :street, 'Calle'
        .control
          = f.text_field :street, class: 'input', required: true
    .column
      .field
        = f.label :city, 'Ciudad'
        .control
          = f.text_field :city, class: 'input', required: true
    .column
      .field
        = f.label :state, 'Estado'
        .control
          = f.text_field :state, class: 'input', required: true
  .columns
    .column
      .field
        = f.label :lat, 'Latitud'
        .control
          = f.number_field :lat,
            class: 'input',
            required: true,
            in: (-90..90),
            step: 0.0000000000001
    .column
      .field
        = f.label :lng, 'Longitud'
        .control
          = f.number_field :lng,
            class: 'input',
            required: true,
            in: (-180..180),
            step: 0.0000000000001
    .column
      .actions: .control: .columns.is-centered: .column.is-three-quarters
        = f.submit 'Guardar', class: 'button is-success is-medium is-fullwidth'

app/views/restaurants/edit.html.slim
.hero.is-success
  .hero-body
    .container
      .columns
        .column.is-1
          = link_to restaurants_path, class: 'button is-success is-large is-outlined is-inverted'
            span.icon
              i.fas.fa-arrow-left
        .column
          h1.title Editar restaurante '#{@restaurant.name}'
          h2.subtitle Cambia los datos necesarios

section.section
  .container: .columns: .column
    == render 'form'

app/views/restaurants/index.html.slim
.hero.is-success
  .hero-body
    .container
      .columns
        .column.is-three-quarters
          h1.title Estos son nuestros restaurantes disponibles
        .column.has-text-right
          = link_to new_restaurant_path, class: 'button is-medium is-success is-outlined is-inverted'
            span.icon
              i.fas.fa-plus-circle
            span Nuevo

section.section
  .container: .columns: .column
    .columns.is-multiline
      - @restaurants.each do |restaurant|
        .column.is-half: .card
          = link_to restaurant
            helper.card-header.has-background-primary
              p.card-header-title.has-text-white = restaurant.name
          .card-content: .content
            .site
              .columns
                .column
                  span.has-text-weight-bold Sitio:&nbsp;
                  = link_to restaurant.site, restaurant.site
                .column.has-text-right
                  - restaurant.rating.times do
                    span.icon.has-text-warning
                      i.fas.fa-star
                  - (5 - restaurant.rating).times do
                    span.icon
                      i.fas.fa-star
            .contact
              .columns.is-multiline
                .column
                  span.icon
                    i.fas.fa-at
                  span = restaurant.email
                .column.has-text-right
                  span.icon
                    i.fas.fa-phone
                  | &nbsp;
                  span = restaurant.phone
            .location: .columns: .column
              p.has-text-weight-bold Ubicados en
              p
                = restaurant.street
                | ,&nbsp;
                = restaurant.city
                | ,&nbsp;
                = restaurant.state
              p
                span.icon
                  i.fas.fa-map-marker-alt
                span.has-text-weight-bold
                  | Lat.:&nbsp;
                span = restaurant.lat
                | &nbsp;&nbsp;
                span.span.has-text-weight-bold
                  | Long.:&nbsp;
                span = restaurant.lng
          footer.card-footer
            = link_to edit_restaurant_path(restaurant), class: 'card-footer-item has-text-info'
              span.has-text-warning
                span.icon
                  i.fas.fa-pen
                span Editar
            = link_to restaurant, data: { confirm: "Eliminar restaurante #{restaurant.name}?" }, 
              method: :delete, class: 'card-footer-item'
              span.has-text-danger
                span Eliminar
                span.icon
                  i.fas.fa-times

app/views/restaurants/new.html.slim
.hero.is-success
  .hero-body
    .container
      .columns
        .column.is-1
          = link_to restaurants_path, class: 'button is-success is-large is-outlined is-inverted'
            span.icon
              i.fas.fa-arrow-left
        .column
          h1.title Agregar nuevo restaurante
          h2.subtitle Llena el formulario con los datos del nuevo restaurante

section.section
  .container: .columns: .column
    == render 'form'

app/views/restaurants/show.html.slim
.hero.is-success
  .hero-body
    .container
      .columns
        .column.is-1
          = link_to restaurants_path, class: 'button is-success is-large is-outlined is-inverted'
            span.icon
              i.fas.fa-arrow-left
        .column
          span.title = @restaurant.name
          | &nbsp;
          = link_to edit_restaurant_path(@restaurant), class: 'is-size-4'
            span.icon
              i.fas.fa-pen
        .column.is-2.has-text-right.is-size-5
          - @restaurant.rating.times do
            span.icon.has-text-warning
              i.fas.fa-star
          - (5 - @restaurant.rating).times do
            span.icon
              i.fas.fa-star

section.section
  .container: .columns: .column
    p#notice = notice
    .columns: .column
      span.title.is-3
        | Sitio Web:&nbsp;
        = link_to @restaurant.site, @restaurant.site, class: 'is-size-3'
    .columns: .column
      h3.title.is-3 Contacto
      .columns
        .column.has-text-centered
          span.title.is-4
            span.icon
              i.fas.fa-at
            | &nbsp;&nbsp;
            span = @restaurant.email
        .column.has-text-centered
          span.title.is-4
            span.icon
              i.fas.fa-phone
            | &nbsp;&nbsp;
            span = @restaurant.phone
    .columns: .column
      h3.title.is-3 Dirección
      .columns
        .column
          h5.title.is-5 Calle
          span.is-size-6 = @restaurant.street
        .column
          h5.title.is-5 Ciudad
          span.is-size-6 = @restaurant.city
        .column
          h5.title.is-5 Estado
          span.is-size-6 = @restaurant.state
    .columns: .column
      h3.title.is-3 Ubicación
      .columns
        .column.has-text-centered
          span
            span.title.is-5 Latitud:
            | &nbsp;&nbsp;
            span.is-size-5 = @restaurant.lat
        .column.has-text-centered
          span
            span.title.is-5 Longitud:
            | &nbsp;&nbsp;
            span.is-size-5 = @restaurant.lng